### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by dennishzg**
### What is the purpose of this pull request?
1. fix typo

#### Changes
- [x] fixed typo (Hats -> Crying -> Description)

### CODE REVIEW

**Comment by datatags** [comment]
Isn't it in reference to the meme "I Cri Evrytiem" ?

**Comment by dennishzg** [comment]
I didn't know about that meme 😄 . But yes it should be either "I cry every time" or "I Cri Evrytiem".

**Comment by datatags** [comment]
I vote "I cri evrytiem". If that sounds good you can go onto your fork and edit the file in your branch [fix-typo-6](https://github.com/dennishzg/UltraCosmetics/tree/fix-typo-6) to update the PR.

**Comment by dennishzg** [comment]
done. pr is ready to be merged.

**Comment by datatags** [comment]
Thanks! 🙂

**Pull request merged**
