### PR TITLE
Add security policy

### PR DESCRIPTION
**Pull request by dennishzg**
### What is the purpose of this pull request?
1. Add a security policy to the repository. ([https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository))

#### Changes
- [x] Added SECURITY.md file

### CODE REVIEW

**Comment by Chris6ix** [comment]
I don't really get the use for this...
The fact that we only support the latest version doesn't really have anything to do with "security" imo
And I don't believe there are any real "vulnerabilities" that this plugin can have that would be "unsafe" or something if they get just normally reported (Github issues or Discord)

If there is a specific reason for only reporting something directly to datatags then please let me know, as I can't think of one...

**Comment by dennishzg** [comment]
@Chris6ix 

"We only support the latest release..." means that we are not going to fix any potential vulnerabilities in old versions. For example when v3 is released we will not fix any vulnerabilities in v2.9. (If this is not the case, i will edit the text.) 

I think this was a vulnerability in an old version: https://github.com/iSach/UltraCosmetics/issues/314 ("Fixed an issue where the trampoline would permanently remove the blocks the ladders replaced.")
Griefers could have abused that bug.

If someone finds a vulnerability they know where to report it. Sometimes unexpected things can happen, you never know. I mean, it can't hurt to add this. I don't see any disadvantages.

**Comment by Chris6ix** [comment]
> I think this was a vulnerability in an old version: [iSach#314](https://github.com/iSach/UltraCosmetics/issues/314) ("Fixed an issue where the trampoline would permanently remove the blocks the ladders replaced.") Griefers could have abused that bug.
> 
> If someone finds a vulnerability they know where to report it. Sometimes unexpected things can happen, you never know. I mean, it can't hurt to add this. I don't see any disadvantages.

Okay that's fair. I guess just make clear that this is only meant for real vulnerabilities that can be abused by for example griefers and not for just every normal bug, just so that datatags dms don't get spammed with tons of bug reports.

Even better would be to just add that small note into the Github issues template, as I don't believe a lot of people will look at this "security" file.

**Comment by dennishzg** [comment]
@Chris6ix 

(In case you didn't know: The SECURITY.md file is a feature of GitHub for the [Security page](https://github.com/datatags/UltraCosmetics/security) of this repository. You don't open the SECURITY.md file directly.)

It should be very obvious that the **Security** tab is for vulnerabilities and not for bugs because the word "bug" isn't mentioned anywhere... and it's called "Security"... and the description on the Security page says: "View how to securely report security vulnerabilities for this repository".

> "Even better would be to just add that small note into the GitHub issues template..."

⚠️ GitHub does that automatically after you add the SECURITY.md file. It looks like this: [Example](https://github.com/nuxt/framework/issues/new/choose).

I am working on a PR that improves the README.md! The changes i am working on make everything clearer and unmistakable. The new README.md contains links and explanations for bug reports (at the top) and vulnerability reports (at the bottom). 👍

**Comment by Chris6ix** [comment]
Oh, I was not aware that was a real feature that showed up like that in the issue templates.
In that case sure why not.
Thanks for explaining it tho👍

**Comment by datatags** [comment]
Seems like a good idea. I usually keep my DMs from non-friends off though because people will DM me for support just because they can instead of using the UC server. So I'm trying to figure out how that should work

**Comment by dennishzg** [comment]
I see, that makes sense 😄. The most common approach is to use an email address. I believe Google Forms is another great alternative. Post the link of the form and i will edit the PR.

**Comment by datatags** [comment]
How does this look? https://forms.gle/ByL6rZTdRvJwb2SK6

**Comment by dennishzg** [comment]
Replace "issue" with "vulnerability" everywhere. Everything else looks good to me 👍.
The link doesn't change when you edit the form, right?

**Comment by datatags** [comment]
> Replace "issue" with "vulnerability" everywhere.

Done, and yeah the link's still the same.

Thanks!

**Pull request merged**
