### PR TITLE
fix typo "BigSmile"

### PR DESCRIPTION
**Pull request by dennishzg**
### What is the purpose of this pull request?
1. fix typo

#### Changes
- [x] fixed typo (Hats -> BigSmile -> Name)

### CODE REVIEW

**Comment by datatags** [comment]
Good idea, I might actually do "Big <ins>S</ins>mile" though to keep capitalization consistency with the other hats like "Command Block"

**Comment by dennishzg** [comment]
"Allow edits by maintainers" is enabled, just push a commit to this pr if you want to change it. 👍

**Comment by datatags** [comment]
Done, thanks 😄

**Comment by dennishzg** [comment]
@datatags I think we shouldn't fix typos or change existing strings in the messages_en.yml file via GitHub anymore. Every time a change is made we have to add all the translations for that string again. Or is this the intended behaviour 🤔? It's really annoying to add all the translations again after fixing a small typo 😅.  Can you edit the source strings in the Crowdin editor? Would that solve this issue? I can report mistakes in source strings directly on Crowdin.

**Comment by datatags** [comment]
I think this is intended, whether on Crowdin or GitHub. because, for example, when we changed "Let it go" to "Let it snow" for the Blizzard Blaster gadget, that does actually require a change in other languages, and Crowdin can't really know what changes meaningfully change the string.

There is some finite amount of typos in the english though, so once we correct them all, it shouldn't happen as much. Plus, Crowdin does re-suggest similar translations when you're in the editor, so you don't have to start from scratch on all the changed strings.

**Comment by dennishzg** [comment]
Okay i understand. Yes the "Translation Memory" feature is very useful.

**Pull request merged**
