### PR TITLE
README.md improvements

### PR DESCRIPTION
**Pull request by dennishzg**
### What is the purpose of this pull request?

1. Add useful information to README.md (especially for regular users/non-developers)
2. Fix and optimize a few things (markdown code, code formatting, ...)

Preview for README.md: https://github.com/dennishzg/UltraCosmetics/tree/improve-readme

#### Changes

- [x] The logo file is now stored in the repository
- [x] Removed wiki badge because of the new "Documentation" section
- [x] Removed LGTM badge (#27) 
- [x] Removed last commit badge (This information is already at the top of the repository page, just scroll up a bit)
- [x] Replaced blurry Discord badge with a Discord badge from [shields.io](http://shields.io/)
- [x] Added SpigotMC downloads badge
- [x] Added "Compatibility" section
- [x] Added "Download" + "Development Builds" section
- [x] Added "Documentation" section
- [x] Added "Report a Bug" section
- [x] Added "Translations" section
- [x] Added "Support" section
- [x] Added "Development" section
- [x] Added CI status badge
- [x] Added CodeQL status badge
- [x] Added "License" section
- [x] [Table of Contents support](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/) for README.md
- [x] Added emojis to the issue template names
- [x] Fixed code formatting in `BUG_REPORT.yml` and `FEATURE_REQUEST.yml`
- [x] Added "Documentation" link and emojis to `ISSUE_TEMPLATE/config.yml`

### CODE REVIEW

**Comment by Chris6ix** [comment]
Looks really nice, I like it!
I just have a few suggestions:

The small table in the Compatibility section seems a little redundant as there is only 1 entry, so i would suggest removing that and including the "1.8.8 to latest" into the sentence above.
Or you could just link the [Compatibility page](https://github.com/datatags/UltraCosmetics/wiki/Supported-Configurations) from the Wiki

A small visual improvement would be in the Downloads section to change the first sentence to "You can download the latest stable release of UltraCosmetics [on Spigot](https://www.spigotmc.org/resources/10905/)" instead of having just the link there.
You did this in no other spot, so I'm not sure why you did that here?

I would not link the Actions Tab for the development builds, as we can't really recommend the builds from there, as sometimes they have non-complete features or are not yet tested.
It would be much better if the non developers of UC don't use these builds and instead only use the "official" dev builds posted in the discord.

For the Translations section I would change the first sentence to "Supported languages: English, Spanish, German, Chinese Simplified and [more](https://crowdin.com/project/ultracosmetics)" so that we don't have to update that every time a new language gets added

I would also remove the "Java CI" badge from the top, as that doesn't really provide any valuable info to the average user, and it also links to the Actions Tab, which as I already said shouldn't really be accessed (Or downloaded from) by the average user.

Please tell me what you (or datatags) think of these suggestions 😁

**Comment by dennishzg** [comment]
Thanks for the suggestions. I will make some changes.

**Comment by Chris6ix** [comment]
Looks a lot better!

Just a tiny nitpick, as it's only 1 link:
image

Otherwise, looks good to me 😅

**Comment by datatags** [comment]
Looks amazing, thanks so much! 😄

**Pull request merged**
