### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Chris6ix**
### What is the purpose of this pull request?

Just updates a few dependencies
I also tried updating `HikariCP` from `4.0.3` to `5.0.1`, but that [failed to build](https://github.com/Chris6ix/UltraCosmetics/actions/runs/3154301952/jobs/5131742878#step:8:50) with a Java version error, which I am not sure how to fix.

### CODE REVIEW

**Comment by datatags** [comment]
Yes, newer versions of Hikari are compiled with Java 11 while UC core is compiled with Java 8. We could move the hikari dependency to another subproject (like how it is with WorldGuard) and drop support for MySQL on Java 8 though.

**Comment by Chris6ix** [comment]
Oh, alright, so just [like this](https://github.com/Chris6ix/UltraCosmetics/commit/074233771d9004d47f7d4e73da1f16bdca41bd28), or should I also remove Hikari from the core dependencies? (Because you said "drop support for MySQL on Java 8")
I tried it in a test branch, and it [builds fine](https://github.com/Chris6ix/UltraCosmetics/actions/runs/3158526396) like that.

**Comment by datatags** [comment]
I was thinking I'd put it in its own project called `hikari` or something so I don't have to worry about moving it if/when we decide to remove the `v1_18_R2` NMS module. Plus, then we can be more specific about the Java version it uses.

**Comment by datatags** [comment]
Thanks!

**Pull request merged**
