### PR TITLE
All Mobs as pets

### PR DESCRIPTION
**Pull request by Chris6ix**
### What is the purpose of this pull request?
Adds all the remaining Vanilla Mobs as pets to UC
Will try to complete for UC 3
#### Changes
- [x] Added Cod pet
- [x] Added Donkey pet
- [x] Added Mule pet
- [x] Added Pufferfish pet
- [x] Added Glow Squid pet (Disabled because of lack of movement)
- [x] Added Ocelot pet
- [x] Added Salmon pet
- [x] Added Skeleton Horse pet
- [x] Added Squid pet (Disabled because of lack of movement)
- [x] Added Strider pet
- [x] Added Tadpole pet
- [x] Added Tropical Fish pet
- [x] Added Turtle pet
- [x] Added Wandering Trader pet
- [x] Added Cave Spider pet (Not Tested)
- [x] Added Dolphin pet (Not Tested)
- [x] Added Spider pet (Not Tested)
- [ ] Added Trader Llama pet
- [ ] Added Zombified Piglin pet
- [ ] Added Drowned pet
- [ ] Added Elder Guardian pet
- [ ] Added Endermite pet
- [ ] Added Evoker pet
- [ ] Added Ghast pet
- [ ] Added Guardian pet
- [ ] Added Hoglin pet
- [ ] Added Husk pet
- [ ] Added Magma pet
- [ ] Added Phantom pet
- [ ] Added Piglin Brute pet
- [ ] Added Pillager pet
- [ ] Added Ravager pet
- [ ] Added Shulker pet (If that even works)
- [ ] Added Stray pet
- [ ] Added Vindicator pet
- [ ] Added Witch pet
- [ ] Added Wither Skeleton pet
- [ ] Added Zoglin pet
- [ ] Added Zombie Villager pet
- [ ] Added Zombie Horse pet
- [ ] Added Illusioner pet
#### Some improvements/fixes to do:
- Add Description to Dolphin
- Reduce speed for Wandering Trader
- Increase speed for Cod, Salmon, Skeleton Horse, Tadpole, Tropical Fish, Turtle
- Maybe try to get the strider to feel like it's in lava all the time so that it looks better and moves faster

### CODE REVIEW

**Comment by datatags** [comment]
Wow! This is gonna be a lot!

One thing that would be cool that just came to mind is that instead of preventing the zombie pet from converting to a drowned, it converts to a drowned pet if the user has it unlocked.

**Comment by Chris6ix** [comment]
> Wow! This is gonna be a lot!
> 
> One thing that would be cool that just came to mind is that instead of preventing the zombie pet from converting to a drowned, it converts to a drowned pet if the user has it unlocked.

Sure, I would just say that this should be a setting for the individual user then (Maybe a toggle when you right-click the zombie in the menu?), because I can imagine that either some people wouldn't like that because they expect cosmetics to stay the same no matter what (Such as cosmetic animals never growing up) or it could be interpreted by some people like a bug because they expect cosmetics to not change like that.

**Comment by datatags** [comment]
> > Wow! This is gonna be a lot!
> > One thing that would be cool that just came to mind is that instead of preventing the zombie pet from converting to a drowned, it converts to a drowned pet if the user has it unlocked.
> 
> Sure, I would just say that this should be a setting for the individual user then (Maybe a toggle when you right-click the zombie in the menu?), because I can imagine that either some people wouldn't like that because they expect cosmetics to stay the same no matter what (Such as cosmetic animals never growing up) or it could be interpreted by some people like a bug because they expect cosmetics to not change like that.

Fair enough 🤷 

Looking over this list, I'm glad that these additions need not support 1.8 because several of these would require extra special handling (skeleton horse, zombie villager, cat vs ocelot, etc)

Also I noticed the zombie horse isn't in the list?

**Comment by Chris6ix** [comment]
> Looking over this list, I'm glad that these additions need not support 1.8 because several of these would require extra special handling (skeleton horse, zombie villager, cat vs ocelot, etc)
> 
> Also I noticed the zombie horse isn't in the list?

Yeah, I can imagine that could be annoying to implement then  :)

The cat vs ocelot thing seems to already work fine tho...when it detects any version below 1.14, it registers the "Kitty" pet using an ocelot, and when you run 1.14+ it registers both the "Kitty" pet using the cat and the "Ocelot" pet using the ocelot

Yeah, I know, that's because I used [this list](https://minecraft.fandom.com/wiki/Mob#List_of_mobs) to see what mobs are in the game and the Zombie Horse falls under the "unused mobs"...that's why I also didn't add the Illusioner to the list.
But if you want, then I can also add these 2 to the list.

I also noticed in the [TODO list here github](https://github.com/datatags/UltraCosmetics/blob/master/TODO.txt) that there were plans to also add the different Jockeys as pets?
I also wanted to do those, but I'm not sure tho if that even works because there doesn't seem to be a "Spider Jockey" entity for example...jockeys are basically just 2 entities strapped together...so I'm not sure how I would do that here to create a pet...

**Pull request closed without merging**
