### PR TITLE
Fix messages files pr guideline in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dennishzg**
### What is the purpose of this pull request?

I fixed the pull request guideline in the CONTRIBUTING.md regarding Crowdin and the messages files. 
It's the right and intended behavior that Crowdin loses translations when you modify a source string, otherwise we would have wrong/old translations in the translation files. 
Typos in source strings should be fixed on Crowdin, because they don't have to be translated again.

### CODE REVIEW

**Comment by datatags** [comment]
Can you confirm you're able to add strings to the project on Crowdin? I asked someone to do it at some point and they couldn't find the button, so I'm not sure if it's something only I can do or not.

**Comment by dennishzg** [comment]
No, I can't add new strings, only admins should be able to do that. But why do you want to add new strings through Crowdin, I'm confused 🤔. The correct way to add new strings should be through GitHub, for example when you add new cosmetics or when you change a description etc.

**Comment by datatags** [comment]
I guess I misunderstood what you said here then:
> - Do not submit pull requests that add translations.
>    Please submit translations through [Crowdin](https://crowdin.com/project/ultracosmetics).

Maybe it would be helpful to clarify that, or specifically say that adding new strings is allowed

**Comment by dennishzg** [comment]
The strings in the messages_en.yml are not translations, they are the source strings. I added that guideline to prevent pull requests like #45 and #42.

**Comment by datatags** [comment]
Right, so maybe it should say something along the lines of, "adding source strings is OK," just so it's clear (in addition to what you already have there.)

**Comment by dennishzg** [comment]
Done.
(Sorry, I always forget to add `[ci skip]` 🤯)

**Comment by datatags** [comment]
Looks good, thanks!

**Pull request merged**
